[build]
bin = "tmp/server"
cmd = "templ generate && go build -o ./tmp/ ./cmd/server/."
exclude_dir = ["tmp", "node_modules", "styles"]
exclude_regex = ["_test.go", ".*_templ.go"]
include_ext = ["go", "tpl", "tmpl", "templ", "html", "yml"]
poll_interval = 1000
delay = 1000
