# fly.toml app configuration file generated for rs-tools on 2023-12-11T19:41:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rs-tools"
primary_region = "lhr"

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
